### PR TITLE
pretrained parcnet

### PR DESCRIPTION
**Pull request by seannz**
– pretained model file (*.ckpt)
– requirements (parcnet_demo.py)
– inference script (parcnet_demo.py)

### CODE REVIEW

**Comment by Aakanksha-Rana** [comment]
@seannz @Hoda1394 amm, I dont think we want to put it in neuronets...

**Comment by seannz** [comment]
Oops sorry—should I move it up one level? Do you have a naming convention in mind? Perhaps MGH/parcnet?

**Comment by satra** [comment]
@seannz - perhaps you could create an org called `lcn`

**Comment by seannz** [comment]
@satra @Aakanksha-Rana @Hoda1394, done!

**Comment by satra** [comment]
to minimize size of the repo, we are not storing the weights in this repo. @Hoda1394 can add it to the trained-models repo. and a new PR without the weights should be sent here so that the weights don't get recorded in the git history.

**Comment by seannz** [comment]
Ah okay, please have a look now! I can email Hoda the pre-trained model (and example image) separately!

**Comment by Hoda1394** [comment]
I will take care of it.

**Comment by Hoda1394** [comment]
@seannz - we need a version number based on [semantic versioning](https://semver.org/).
also, can you share the pre-trained model file with us maybe through dropbox or any other way?

**Comment by Hoda1394** [comment]
@seannz - Also please create a requirements.txt file with main software dependencies and their version to replicate your environment.

**Comment by seannz** [comment]
How about we include this in the model repository, rather than in the zoo? The reasoning is that different FS versions (not to mention different cortical models) produce slightly different parameterizations so just feeding them to a pretrained cortical parcellation net would produce garbage results. (Still trying to familiarize myself with how Nobrainer releases work.)

As for the requirements, there's really only pytorch (1.9.0) since this is a model not an entire framework.

**Comment by satra** [comment]
@seannz - `zoo` is still the right place for the model. the `nobrainer` library is tensorflow only and if we reimplement the parcnet model in tensorflow, then we should put it in the library.  thus anything trained, would be distributed through the zoo + trained-models. anything coded in tensorflow 2.x can be included in the nobrainer library. 


for users to use the model, they can use the zoo, which works with containers/standalone environments. users can be told via a README that the input has to be from a specific version of freesurfer if that is the case. this all can be done at the level of how the model is executed.

**Comment by seannz** [comment]
Thanks @satra, yes let's put this in the zoo as originally planned—I can always update the pre-trained model with a newer one if required. I'll email @hoda the requested files. Thanks!

**Comment by seannz** [comment]
I'm only used to writing research code and not very familiar with release cycles. Bear with me this once; I'll get better!

**Comment by satra** [comment]
>  Bear with me this once; I'll get better!

no worries. there is some training for everyone in something with this project :)

**Comment by Hoda1394** [comment]
@seannz - we did some restructuring of the zoo recently and moved the model-related files to the [trained-model](https://github.com/neuronets/trained-models/tree/master/lcn/parcnet/1.0.0) repository. 
So I added your files there. I also made a little change to punet.py to accept the model file path as an input rather than assuming the weights are located in the same folder. I am closing this PR since parcnet is added to [trained-model](https://github.com/neuronets/trained-models/tree/master/lcn/parcnet/1.0.0).
In general, I suggest having all parent files in a separate Github repository. So we can follow the revisions of the model and the code. So let me know if you create one.

**Pull request closed without merging**
