### PR TITLE
Merge into main

### PR DESCRIPTION
**Pull request by satra**
@Hoda1394 - this should be merged into main right?

### CODE REVIEW

**Comment by Hoda1394** [comment]
I tagged the main, this one can be merged and then I can collect feedback before we release it.

**Comment by satra** [comment]
this option makes infile optional. what is the use case for that?

`nobrainer-zoo predict [OPTIONS] [INFILE]... OUTFILE`

**Comment by satra** [comment]
i get this exception from datalad 

> datalad.support.exceptions.MissingExternalDependency: git-annex of version >= 7.20190503 is missing. Visit http://handbook.datalad.org/r.html?install for instructions on how to install DataLad and git-annex.

although i have git-annex version `10.2022...`

**Comment by satra** [comment]
i was running this command: `nobrainer-zoo predict -m UCL/SynthSeg/1.0.0 --container_type docker ~/Downloads/BCP_infants_segmentation_share_test/sub-380056/ses-4mo/anat/sub-380056_ses-4mo_run-001_T1w.nii.gz sub-380056_ses-4mo_run-001_seg.nii.gz`

**Comment by satra** [comment]
also cannot run this on dandihub.

```
$ nobrainer-zoo predict -m UCL/SynthSeg/1.0.0 $(pwd)/sub-380056/ses-4mo/anat/sub-380056_ses-4mo_run-001_T1w.nii.gz sub-380056_ses-4mo_run-001_seg.nii.gz
/usr/bin/python3: can't open file '/opt/conda/lib/python3.9/site-packages/nobrainerzoo/download.py': [Errno 2] No such file or directory

https://github.com/BBillot/SynthSeg.git repository is available locally
Using TensorFlow backend.


SynthSeg prediction


Traceback (most recent call last):
  File "/home/jovyan/.nobrainer/trained-models/UCL/SynthSeg/1.0.0/predict.py", line 70, in <module>
    predict(**args)
  File "/home/jovyan/.nobrainer/repo/SynthSeg-1.0.0/SynthSeg/predict.py", line 182, in predict
    nb_conv_per_level, unet_feat_count, feat_multiplier, activation, sigma_smoothing, gradients)
  File "/home/jovyan/.nobrainer/repo/SynthSeg-1.0.0/SynthSeg/predict.py", line 445, in build_model
    assert os.path.isfile(model_file), "The provided model path does not exist."
AssertionError: The provided model path does not exist.
```

**Comment by satra** [comment]
i installed the zoo with this command:

`pip install https://github.com/neuronets/nobrainer-zoo/archive/refs/heads/dev.zip`

**Comment by Hoda1394** [comment]
> this option makes infile optional. what is the use case for that?
> 
> `nobrainer-zoo predict [OPTIONS] [INFILE]... OUTFILE`

We have no use case for the optional infile for the predict function. but click shows it in brackets since we can have multiple infiles. for UCL/SynthSR/1.0.0/hyperfine we need more than one infile.

**Comment by Hoda1394** [comment]
> i get this exception from datalad
> 
> > datalad.support.exceptions.MissingExternalDependency: git-annex of version >= 7.20190503 is missing. Visit http://handbook.datalad.org/r.html?install for instructions on how to install DataLad and git-annex.
> 
> although i have git-annex version `10.2022...`


datalad and git annex are running in the container we do not need them installed on the system. I will check to see why such error happend.

**Comment by Hoda1394** [comment]
> also cannot run this on dandihub.
> 
> ```
> $ nobrainer-zoo predict -m UCL/SynthSeg/1.0.0 $(pwd)/sub-380056/ses-4mo/anat/sub-380056_ses-4mo_run-001_T1w.nii.gz sub-380056_ses-4mo_run-001_seg.nii.gz
> /usr/bin/python3: can't open file '/opt/conda/lib/python3.9/site-packages/nobrainerzoo/download.py': [Errno 2] No such file or directory
> 
> https://github.com/BBillot/SynthSeg.git repository is available locally
> Using TensorFlow backend.
> 
> 
> SynthSeg prediction
> 
> 
> Traceback (most recent call last):
>   File "/home/jovyan/.nobrainer/trained-models/UCL/SynthSeg/1.0.0/predict.py", line 70, in <module>
>     predict(**args)
>   File "/home/jovyan/.nobrainer/repo/SynthSeg-1.0.0/SynthSeg/predict.py", line 182, in predict
>     nb_conv_per_level, unet_feat_count, feat_multiplier, activation, sigma_smoothing, gradients)
>   File "/home/jovyan/.nobrainer/repo/SynthSeg-1.0.0/SynthSeg/predict.py", line 445, in build_model
>     assert os.path.isfile(model_file), "The provided model path does not exist."
> AssertionError: The provided model path does not exist.
> ```

This error can happen for two reasons.  the NOBRAINER_CACHE variable was set in the previous session and it is not passed in the new session so nobrainer-zoo is looking in the wrong location or there was an error while datalad downloads the model so model was not downloaded and not available. I will check it

**Comment by satra** [comment]
it may be helpful to provide some logging perhaps even debug logging about the steps being executed, so we know what the zoo cli is doing. i created a project for the ohbm hackathon to work on nobrainer so we can refine some of this to be clear to the user. we should also consider the nobrainer-zoo docker image to be as small as possible. currently the `neuronets/nobrainer-zoo:nobrainer` image is 7G expanded. perhaps we can create a base image that is just datalad+git-annex in as small a footprint as possible, and this is used for the cli operations and then any image associated with a model is as defined by the model.

**Comment by Hoda1394** [comment]
yes it is better to have a light image just for the basic zoo operations. The reason that I merged it with nobrainer image is to have fewer containers. I can separate it quickly. About the logger, what type of document it should be?

**Comment by satra** [comment]
> About the logger

i simply meant [python logging](https://docs.python.org/3/howto/logging.html)

**Comment by Hoda1394** [comment]
ok got it.

**Pull request merged**
